### ISSUE TITLE
Failed build -> Error on Flutter Channel stable 2.5.2

### ISSUE THREAD

**Issue by RoisNewVersion** [indratrisnar/d_chart#1]
Just upgrade my flutter to the latest version, and got error like this.
`color ??= Theme.of(context).textTheme.body1!.color`
The problem is ini `.body1`

**Comment by indratrisnar** [comment]
the problem is not based on the package, but the outdated flutter dart
code. you have to change the way you use the color style

Pada tanggal Jum, 8 Okt 2021 13.38, roisul ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
please explain in more detail regarding the error that appears.
when does the error appear?
is it when you try to style the chart, or use some properties in d_chart or
what?
and have you tried the example?

Pada tanggal Min, 10 Okt 2021 16.17, roisul ***@***.***>
menulis:

**Comment by RoisNewVersion** [comment]
Sorry, if it wasn't clear enough.
here's the chronology.

- I was using this plugin and running well
- I decide to upgrade my flutter to the latest stable version (now 2.5.2)
- I tried `flutter build appbundle` and got error like this `/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/charts_flutter-0.11.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'body1' isn't defined for the class 'TextTheme'.`

I hope it helps, thanks.

**Comment by indratrisnar** [comment]
Oke i'll chek it.
This package build depends on flutter 2.5.0.
I will try to upgrade to the last stable version.
Have you run on debug mode? Is it run well or something wrong?

Pada tanggal Min, 10 Okt 2021 18.57, roisul ***@***.***>
menulis:

**Comment by RoisNewVersion** [comment]
yes, debug mode also stuck on the same error.

**Comment by indratrisnar** [comment]
i have found something error depends on base package where the package is
charts_flutter.
the issue:
/
C:/Users/Divcase/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/charts_flutter-0.11.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45:
Error: The getter 'body1' isn't defined for the class 'TextTheme'.

for the time being d_chart is still under construction, so it can't be used
yet. After fixing it, I'll let you know later
thank you for understanding

Pada tanggal Min, 10 Okt 2021 pukul 20.35 roisul ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
Package D'Chart has updated. Bug fixed.

Pada tanggal Min, 10 Okt 2021 22.52, Indra Trisna ***@***.***>
menulis:
