### ISSUE TITLE
 DRenderPoint not showing chart

### ISSUE THREAD

**Issue by carzelsoft** [indratrisnar/d_chart#13]
when use the example  DChartTime with  DRenderPoint not showing chart

**Comment by indratrisnar** [comment]
Have you try restart?

Pada tanggal Sel, 25 Apr 2023 05.32, carzelsoft ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
change value with render, you have to restart run build. and now that widget has deprecated. You should use new chart with more optimization use
