### ISSUE TITLE
How to display Line chart in vertical mode instead of horizontal?

### ISSUE THREAD

**Issue by nguyencse** [indratrisnar/d_chart#15]
Thanks for your awesome library @indratrisnar .

I need show DLineChart vertically (expand to fit height of device). How can I do that?
Thanks for your advices.

**Comment by nguyencse** [comment]
ok I just found a simple workaround solution is use RotatedBox

**Comment by indratrisnar** [comment]
you can wrap with RotatedBox or custom rotate with Transform.rotate

Pada tanggal Jum, 23 Jun 2023 pukul 15.39 Nguyen Y Nguyen <
***@***.***> menulis:

**Comment by indratrisnar** [comment]
You can wrap it with RotatedBox or use Transform.rotate

Pada tanggal Jum, 23 Jun 2023 11.47, Nguyen Y Nguyen <
***@***.***> menulis:
