### ISSUE TITLE
donut rounded corner charts

### ISSUE THREAD

**Issue by ravidhwn01** [indratrisnar/d_chart#16]
is there any property which  makes makes rounded corner like this
![image](https://github.com/indratrisnar/d_chart/assets/87488989/86504ee9-aacf-4d48-a90b-d53b7879b083)

**Comment by indratrisnar** [comment]
For now, not available. Next time I hope can figure it out

Pada tanggal Rab, 28 Jun 2023 17.29, Ravi Kumar Dhawan <
***@***.***> menulis:

**Comment by indratrisnar** [comment]
please always check update and see info on changelog if there is update

**Comment by VuThienHung** [comment]
Hi @indratrisnar 
i have just upgraded the lib to 3.0.0
But i dont know how to use the donut chart like above
Can you help me?
Thanks
