### ISSUE TITLE
Please bring back xAxisTitle and yAxisTitle

### ISSUE THREAD

**Issue by tajjacob** [indratrisnar/d_chart#17]
Please bring back xAxisTitle and yAxisTitle in chart: bar, line, scatter, and combo from previous version.

<img width="472" alt="image" src="https://github.com/indratrisnar/d_chart/assets/63710008/3f5662b8-5683-4b4d-912a-4ae350f5ace9">

<img width="490" alt="image" src="https://github.com/indratrisnar/d_chart/assets/63710008/b5a597c3-6484-42d9-98ca-2a327be09061">

**Comment by indratrisnar** [comment]
I'm still considering is title chart will add to new style chart or not.
For now, you can wrap DChart include widget wrapper with Column/Row then
add Text at top/bottom or Left/Right of Chart.
For vertical direction text, you can wrap Text with DecoratedBox

Pada tanggal Sel, 12 Sep 2023 14.49, Taj Jacob ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
if it still worth to add this property, i will add and you can monitor on changelog.
