### ISSUE TITLE
DChartBarCustom Domain Line and values not showing

### ISSUE THREAD

**Issue by Jonathan-de-Villiers** [indratrisnar/d_chart#18]
`
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';

import 'package:d_chart/d_chart.dart';

class CBChart extends StatefulWidget {
  const CBChart({
    Key? key,
    this.width,
    this.height,
    required this.data,
    required this.colors,
    this.barSize,
  }) : super(key: key);

  final double? width;
  final double? height;
  final List<double> data;
  final List<Color> colors;
  final double? barSize;

  @override
  _CBChartState createState() => _CBChartState();
}

class _CBChartState extends State<CBChart> {
  @override
  Widget build(BuildContext context) {
    return DChartBarCustom(
        valueAlign: Alignment.topCenter,
        showDomainLine: true,
        showDomainLabel: true,
        showMeasureLine: true,
        showMeasureLabel: true,
        spaceDomainLabeltoChart: 0,
        spaceMeasureLabeltoChart: 5,
        spaceDomainLinetoChart: 15,
        spaceMeasureLinetoChart: 20,
        spaceBetweenItem: 16,
        radiusBar: const BorderRadius.only(
          topLeft: Radius.circular(8),
          topRight: Radius.circular(8),
        ),
        measureLabelStyle: const TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 16,
          color: Color.fromARGB(255, 255, 255, 255),
        ),
        domainLabelStyle: const TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 16,
          color: Color.fromARGB(255, 255, 255, 255),
        ),
        measureLineStyle: const BorderSide(
            color: Color.fromARGB(255, 255, 255, 255), width: 2),
        domainLineStyle: const BorderSide(
            color: Color.fromARGB(255, 255, 255, 255), width: 2),
        listData: List.generate(widget.data.length, (index) {
          return DChartBarDataCustom(
            elevation: 3,
            color: widget.colors[index],
            label: index.toString(),
            labelCustom: Text('Test'),
            value: widget.data[index],
            showValue: true,
          );
        }));
  }
}
`

**Comment by indratrisnar** [comment]
did you get error in console?

**Comment by indratrisnar** [comment]
i have tested your code, and it works.
The domain and value lines are displayed.

If you don't see it, it's probably because you put white on the domain line and label. where the background color you use is white.

**Comment by Jonathan-de-Villiers** [comment]
Well, I'm Using the package in Flutterflow so maybe it is just the Flutterflow preview. Thanks! I'll Run it in an emulator to check!
