### ISSUE TITLE
legends

### ISSUE THREAD

**Issue by sasi765** [indratrisnar/d_chart#2]
hello, in this piechart how to give legands. in top of the screen?

**Comment by indratrisnar** [comment]
hi,
for chart in this package,  i don't remember to setting legend. but for
label? available.

for create legend you can set custom.
you can place legend at left, top, right, bottom use Column/Row widget. for
showing at front/back,  you can use Stack widget.
for label,  you can see at the example.

i hope this help you

Pada tanggal Jum, 13 Mei 2022 11.56, sasi765 ***@***.***>
menulis:

**Comment by sasi765** [comment]
okay Thank you.
