### ISSUE TITLE
Desired min tick count on Domain axis

### ISSUE THREAD

**Issue by tmsbrndz** [indratrisnar/d_chart#22]
Hi,

I'm using `DChartBarT` widget for showing values with dates. It is possible to increase tick count on domain axis? 

![image](https://github.com/indratrisnar/d_chart/assets/31684353/9e10663e-0411-4284-a2b2-cbbab8bedf0e)

**Comment by indratrisnar** [comment]
For tick count domain axis time series. It is auto wrap to width of chart
widget. The wider widget, there are more tick label to show.

From gallery community_charts_flutter. There are no sample to set count of
domain tick label.

But you can try with modify domain tick formatter, to set width label as
short as possible.

I think i will add this issue to next version d_chart to manage domain axis
label/tick.


Pada Kam, 4 Jan 2024 18.11, Tamás Brindza ***@***.***>
menulis:

**Comment by tmsbrndz** [comment]
@indratrisnar  Thanks for reply. I will close the issue due to I moved `community_charts_flutter` package.
