### ISSUE TITLE
Horizontal Scrolling

### ISSUE THREAD

**Issue by gilmarferrari** [indratrisnar/d_chart#23]
Is it possible to make a horizontal scroll using DChartBarO? My chart has 5 columns and, depending on the device, the bar labels look quite weird, even reducing the font size. I considered using vertical as false, but it just looks nicer the default way. Anyway, just a question. If it's not possible, no problem, I'll find a workaround.

**Comment by indratrisnar** [comment]
Still not available on d_chart. I'l try add this feature to next version of
d_chart.
If urgent, u can try this:
https://juliansteenbakker.github.io/community_charts/flutter/example/behaviors/sliding_viewport_on_selection

Pada Kam, 11 Jan 2024 03.54, Gilmar Ferrari Filho ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
I have added a horizontal scrolling feature. With new property
'allowSliding'. And other recommendarion rules in its use. Please check new
version of d_chart: 2.6.5

Pada Kam, 11 Jan 2024 05.45, Indra Trisna ***@***.***>
menulis:

**Comment by gilmarferrari** [comment]
Thanks, appreciate it!
