### ISSUE TITLE
DChartPieO not show labels 

### ISSUE THREAD

**Issue by Paroca72** [indratrisnar/d_chart#24]
Hi,

Unfortunately if I try to open the documentation (https://flutterdlux.netlify.app/d_chart/widgets/pie/) I got a "Privacy Error" and the browser not let me go further unless I not disable all the protection.

So, kindly I'm asking here how to show the labels on DChartPieO because by default I not seen them and also using customLabel.
My code:
```
     List<OrdinalData> ordinalList = widget.data
        .map((e) => OrdinalData(
              domain: e["name"] ?? "",
              measure: (e["value"] ?? "").toString().toDouble("en_UK") ?? 0.0,
            ))
        .toList(growable: false);

    return DChartPieO(
            data: ordinalList,
          );
```

Thanks for your help

**Comment by indratrisnar** [comment]
The web documentation changed. For details cek to dchart.netlify.app

Pada Rab, 21 Feb 2024 15.15, Sam ***@***.***> menulis:

**Comment by Paroca72** [comment]
Thanks for the quick reply but as I wrote before I cannot access also to https://dchart.netlify.app/docs/properties/custom-label.
I got always a "Privacy Error" and the browser not let go further.

**Comment by indratrisnar** [comment]
customLabel: (numericData, index) {
    return '${numericData.domain}: ${numericData.measure} kg';
},

customLabel: (ordinalData, index) {
    return '${ordinalData.domain}: ${ordinalData.measure}';
},

customLabel: (timeData, index) {
    return '${timeData.domain}: ${timeData.measure}';
},


Pada Rab, 21 Feb 2024 17.11, Indra Trisna ***@***.***>
menulis:

**Comment by Paroca72** [comment]
I tried with three different browser and have with all the same issue.
Also from mobile and I got the same issue.. so maybe is my country that block your website.

Can you just tell me why I not see the label? 
is more easy?

Very thanks

**Comment by Paroca72** [comment]
I seen.. very thanks

**Comment by Paroca72** [comment]
I tried also in incognito but the issue persists.

    ```
      List<OrdinalData> ordinalList = widget.data
        .map((e) => OrdinalData(
              domain: e["name"] ?? "",
              measure: (e["value"] ?? "").toString().toDouble("en_UK") ?? 0.0,
            ))
        .toList(growable: false);

    return DChartPieO(
            data: ordinalList,
            customLabel: (ordinalData, index) {
              return '${ordinalData.domain}: ${ordinalData.measure}';
            },
          );
```

Still no see any labels.
I already checked the data and "domain" contains text and "measure" a number.
I'm in web.. maybe the issue is only on web.

Thanks

**Comment by indratrisnar** [comment]
> Thanks for the quick reply but as I wrote before I cannot access also to https://dchart.netlify.app/docs/properties/custom-label. I got always a "Privacy Error" and the browser not let go further.
> 
> <img alt="image" width="564" src="https://private-user-images.githubusercontent.com/8638803/306559728-2e2af833-91c8-490c-9dc5-d920b909c089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjE1MzAsIm5iZiI6MTcwODUyMTIzMCwicGF0aCI6Ii84NjM4ODAzLzMwNjU1OTcyOC0yZTJhZjgzMy05MWM4LTQ5MGMtOWRjNS1kOTIwYjkwOWMwODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTMxMzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzI4YjE4M2Y5ZTA4OWI4ZGFkNTA2ZWU5Njc2ZjE3ZTBjYjgzMThhNmUxYTRlODkwZTFjNThhOTI5NjkzMWI0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qr_w-WP6x6hmJVs4jGgh00snSziZX7z4l09iZNFLRYQ">

usually, u can enter mode advance

**Comment by Paroca72** [comment]
Cannot

<img width="539" alt="image" src="https://github.com/indratrisnar/d_chart/assets/8638803/10b9bd68-f652-4cba-96d2-71e04bb99459">


Anyway also using customLabel in web (on mobile idk) labels are not shown.

Thanks

**Comment by indratrisnar** [comment]
try use this property:

` configRenderPie: ConfigRenderPie(
    arcLabelDecorator: ArcLabelDecorator(),
  ),`

**Comment by indratrisnar** [comment]
that proeprty is alternatively for show label on Pie. also for style the label.

**Comment by indratrisnar** [comment]
Tutorial about DChartPie: https://youtu.be/E6E1T_GzlUU

**Comment by Mapk26** [comment]
The label problem is connected with various paramters. For example the inner label is not shown if you have high labelPadding. Try this configuration:

```
final List<OrdinalData> ordinalDataList = [
    OrdinalData(domain: 'Mon', measure: 5, color: AppColors.secondary),
    OrdinalData(domain: 'Tue', measure: 2, color: AppColors.pink),
    OrdinalData(domain: 'Wed', measure: 9, color: AppColors.grey),
    OrdinalData(domain: 'Thu', measure: 15, color: AppColors.blue),
  ];

AspectRatio(
    aspectRatio: 16 / 9,
    child: DChartPieO(
        data: ordinalDataList,
        animate: true,
        animationDuration: const Duration(milliseconds: 1000),
        customLabel: (ordinalData, index) {
          return 'Test';
        },
        configRenderPie: ConfigRenderPie(
          arcWidth: 40,
          arcLength: 2 * pi,
          startAngle: 1 * pi,
          strokeWidthPx: 4,
          arcLabelDecorator: ArcLabelDecorator(
            labelPosition: ArcLabelPosition.auto,
            insideLabelStyle: const LabelStyle(
              color: Colors.white,
              fontSize: 18,
            ),
            outsideLabelStyle: const LabelStyle(
              color: Colors.white,
              fontSize: 16,
            ),
            labelPadding: 2,
            leaderLineStyle: const ArcLabelLeaderLineStyle(
              color: Colors.blue,
              length: 20,
              thickness: 2,
            ),
            showLeaderLines: true,
          ),
        ),
    ),
  ),
```
