### ISSUE TITLE
Stroke Color on DChartPieO

### ISSUE THREAD

**Issue by Mapk26** [indratrisnar/d_chart#26]
Hi!

I'm trying to play styling the DChartPieO but i can't figure out how to change the stroke color.
It seems to be set on white and cannot be changed.

Thank you

**Comment by indratrisnar** [comment]
this package built on top [community_chart](https://pub.dev/packages/community_charts_flutter). for styling line/stroke/space between segmen chart cannot be removed or re-color. it only can set for stroke width.

If there is a new styling addition for this stroke in [community_chart](https://pub.dev/packages/community_charts_flutter), I will immediately try adding it to the [d_chart](https://pub.dev/packages/d_chart) package.

**Comment by indratrisnar** [comment]
or you can try exploring the package, and if you find a way, you can do a pull-request to this repository
