### ISSUE TITLE
show all labels

### ISSUE THREAD

**Issue by johnareid54** [indratrisnar/d_chart#27]
First of all I think this is a great but I am finding it hard to adjust the domain labels:

<img width="677" alt="Screenshot 2024-03-25 at 18 41 31" src="https://github.com/indratrisnar/d_chart/assets/53974881/aea4991d-f9fc-4a66-b9ed-0cf549f0a0cc">

If you look at the image, it starts with "Mar 17", then 19, 21,23 and 25. 
Is it possible to force all the labels i.e. Mar 17, 18, 19, 20, 21, 22,  23, 24, 25

**Comment by indratrisnar** [comment]
try this way based on the explanation:
Combine property padding and format label.
 How to Show Combo Chart in Flutter (youtube.com)
<https://www.youtube.com/watch?v=wmiRztfZnZw&list=PLMeCG4xYek-OiZKkbBC7ZFvvsbKhr1HJD&index=30>
  (05:03
&  08:00)

for documentation:
Property | DChart
<https://dchart.pages.dev/docs/domain-axis/property#minimumpaddingbetweenlabels>

Pada Sel, 26 Mar 2024 pukul 02.49 johnareid54 ***@***.***>
menulis:

**Comment by johnareid54** [comment]
Great, it only take a few seconds to adjust.

```
domainAxis: DomainAxis(
                  labelFormatterT: (dateTime) => DateFormat("dd").format(dateTime),
                ),
```
