### ISSUE TITLE
Null pointer warning

### ISSUE THREAD

**Issue by murali-cse** [indratrisnar/d_chart#3]
<img width="876" alt="Screenshot 2022-07-27 at 12 36 07 AM" src="https://user-images.githubusercontent.com/63541419/181091670-050a723e-152c-472c-bb16-d68e28581fb5.png">

I m using Flutter version 3.0.3. This warning was showing whenever I used the bar chart. Kindly please fix the issue soon.

**Comment by indratrisnar** [comment]
Hello, thank you for your report

this package is sourced from : https://pub.dev/packages/charts_flutter
where there is no latest update. so we are waiting for the latest update
from author charts_flutter.

this error is a warning, which for details you can read here:
https://stackoverflow.com/a/72255722

Pada tanggal Rab, 27 Jul 2022 pukul 02.16 Murali ***@***.***>
menulis:

**Comment by murali-cse** [comment]
Thank you for your response, sir.
