### ISSUE TITLE
MeasureAxis typo thickLength used instead of tickLength

### ISSUE THREAD

**Issue by BS-Wissem** [indratrisnar/d_chart#33]
Hello,
Thanks for this great package.
Could you please correct the typo in MeasureAxis property thickLength.
Thank you

**Comment by indratrisnar** [comment]
tickLength is property used inside community_charts_flutter. Then i use
same property name

Pada Jum, 16 Agu 2024 21.14, BS-Wissem ***@***.***> menulis:

**Comment by indratrisnar** [comment]
Reference to "tick" / plot point. Not "thick" AS wide

Pada Sab, 17 Agu 2024 01.06, Indra Trisna ***@***.***>
menulis:

**Comment by BS-Wissem** [comment]
You can check the property it is named thickLength which is not correct.

**Comment by indratrisnar** [comment]
Which dchart version you use?

Pada Sab, 17 Agu 2024 01.46, BS-Wissem ***@***.***> menulis:

**Comment by indratrisnar** [comment]
dchart: line 23
https://github.com/indratrisnar/d_chart/blob/master/lib/commons/axis/measure_axis.dart

community_chart_flutter: line 105
https://github.com/juliansteenbakker/community_charts/blob/master/community_charts_common/lib/src/chart/cartesian/axis/draw_strategy/small_tick_draw_strategy.dart

**Comment by BS-Wissem** [comment]
I am using version 2.6.9. Looks it was corrected in version 2.8.0 which I can't use in my project because of Dart version.
Anyway thanks again.

**Comment by indratrisnar** [comment]
You're welcome!

Pada Sab, 17 Agu 2024 03.36, BS-Wissem ***@***.***> menulis:
