### ISSUE TITLE
Option to stack line chart and bar chart

### ISSUE THREAD

**Issue by philipvrx** [indratrisnar/d_chart#34]
![image](https://github.com/user-attachments/assets/afb9dfdf-726b-44d8-bd04-59e8b46c220c)

Currently, I'm using Layout Builder to draw a vertical divider inside it

**Comment by indratrisnar** [comment]
can you show me the dhcart code you are using?

**Comment by philipvrx** [comment]
This is line at 100
`  Widget lineStackBar(BuildContext context) {
    List<Color> theme = [ const Color(0xff5470c6),
    const Color(0xff91cc75),
    const Color.fromARGB(255, 235, 172, 36),];
    
    return SizedBox(
      height: 256,
      child: LayoutBuilder(builder: (context, constraints) {
        double wigdetWidth = constraints.maxWidth;
        double lineY = wigdetWidth - 40;
        double target = lineY - (100/ 100 * lineY);

        return Stack(
          children: [
            DChartBarO(
              fillColor: (group, ordinalData, index) {
                return theme[index!];
              },
              domainAxis: const DomainAxis(noRenderSpec: true),
              measureAxis: MeasureAxis(
              
                // numericViewport:
                //     const NumericViewport(0, 100),
                numericViewport: NumericViewport(
                  0,
                 200),
           
                showLine: true,
                labelFormat: (measure) {
                  return '$measure %';
                },),
              
              vertical: false,
              groupList: [
                OrdinalGroup(
                  id: '1',
                  data:[OrdinalData(
                domain: '0',
                measure: 47.52,
                color: theme[0]),
                OrdinalData(
                domain: '0',
                measure: 49.66,
                color: theme[1]),
                OrdinalData(
                domain: '0',
                measure: 188,
                color: theme[2]),],
                ),
              ],
            ),
            Positioned(
              left: target,
              right: 0,
              top: 0,
              bottom: -20,
              child: const VerticalDivider(
                indent: 20,
                endIndent: 40,
              ),
            ),
          ],
        );
      }),
    );
  }
`

**Comment by indratrisnar** [comment]
I understand the position of the image based on the attached code.
Now, what do you want the chart to display? Can you explain?
I don't quite understand why you are using the variable 'target' while its value is 0.

**Comment by philipvrx** [comment]
So my idea is to use DChartLineN to draw the line if possible
Ah target = 0 is a sample for where draw the line at 100 in range (0 -200)

It's just a formula for calculating variables to find the position to draw a straight line representing 100%.
`(100 * lineY * 2)/ maxValue`

**Comment by indratrisnar** [comment]
is this what you min?

![image](https://github.com/user-attachments/assets/642a2f04-317b-4a2d-8227-d27de323a0ea)

**Comment by philipvrx** [comment]
It's already done by using stack and VerticalDivider with the new target `(100 * lineY * 2)/ maxValue` `maxValue = 200`
but I wanna use DChartLineN for the line

**Comment by indratrisnar** [comment]
except bar, other type chart cannot draw on horizontal direction

**Comment by indratrisnar** [comment]
but if you stack the DchartLineT on top of DCharBarO, it can be.
just replace VerticalDivider with DChartLineT (layoutMargin:0, and noRenderSpec)

**Comment by philipvrx** [comment]
Okay, I guess it will do
Thanks for your support!
