### ISSUE TITLE
Show gridline in chart ?

### ISSUE THREAD

**Issue by DucLongDTH** [indratrisnar/d_chart#35]
Can we show gridline in DChartBarO ? 
i saw in readme have it:
![image](https://github.com/user-attachments/assets/cbaa1bf0-d32d-4f39-bddd-e4f96ef2d414)
but the current code it dont show:
![image](https://github.com/user-attachments/assets/956afdd4-ca21-479f-9710-5677e487e93e)

**Comment by indratrisnar** [comment]
if you look at this reference:
https://juliansteenbakker.github.io/community_charts/flutter/example/axes/gridline_dash_pattern

? maybe.

but it is not yet available for the d_chart package, maybe I will try to
implement it for the next version.

thank you for your criticism and suggestions.

Pada Jum, 4 Okt 2024 15.01, Nguyen Duc Long ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
update new version to 2.9.0 anf then you can try this:
https://dchart.pages.dev/docs/measure-axis/property#usegridline

**Comment by DucLongDTH** [comment]
> update new version to 2.9.0 anf then you can try this: https://dchart.pages.dev/docs/measure-axis/property#usegridline
Nice very fast update <3 thanks you guy
