### ISSUE TITLE
BoxConstraints has NaN values in minHeight and maxHeight

### ISSUE THREAD

**Issue by jesselpereira** [indratrisnar/d_chart#36]
![image](https://github.com/user-attachments/assets/59548af8-2261-4826-a1f9-1f54a658c419)

I get this whenever my values ​​are zero.

```dart
           Expanded(
              child: AspectRatio(
                aspectRatio: 16 / 9,
                child: DChartBarCustom(
                  listData: [
                    DChartBarDataCustom(
                      value: 0,
                      label: 'entradas',
                      color: kGreen500,
                    ),
                    DChartBarDataCustom(
                      value: 0,
                      label: 'saídas',
                      color: kRed500,
                    ),
                  ],
                ),
              ),
            ),
```

**Comment by indratrisnar** [comment]
I'm trying to find a solution for this issue, meanwhile you can try the solution from here:
https://stackoverflow.com/questions/74071645/fluttererror-boxconstraints-has-nan-values-in-minheight-and-maxheight

**Comment by indratrisnar** [comment]
try first solution with github package version:
- use github package, like this:
![image](https://github.com/user-attachments/assets/bf99ec17-14a6-43a5-b6ad-44447a05dd2b)

- restart / re-run again your code

if this way solve this issue, i will update d_chart package with new version

**Comment by indratrisnar** [comment]
for specific commit reference:
![image](https://github.com/user-attachments/assets/8066b127-13ec-4dc4-ad8a-895f954174d5)

**Comment by jesselpereira** [comment]
> try first solution with github package version:
> 
> * use github package, like this:
>   ![image](https://private-user-images.githubusercontent.com/65453071/376398007-bf99ec17-14a6-43a5-b6ad-44447a05dd2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTAzMjksIm5iZiI6MTcyODk1MDAyOSwicGF0aCI6Ii82NTQ1MzA3MS8zNzYzOTgwMDctYmY5OWVjMTctMTRhNi00M2E1LWI2YWQtNDQ0NDdhMDVkZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDIzNTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMGIzZmE3NjZlNzBkNGVlOGU3MTM0NDRjMmY2MmQ2NTJmOWJhMjZiZTc1NDY2ZWE4OTMyMDE4NWU1OTcxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Me4Fwmi_97JNfABoWYJr9VWkxCxLPwyxCoUk4RLm07A)
> * restart / re-run again your code
> 
> if this way solve this issue, i will update d_chart package with new version.
> 
> Note: when you add github package version, you also have to check to your flutter local pub cache, is there any change in d_chart package

Thank you very much, it worked perfectly. The error is gone.

<img width="325" alt="image" src="https://github.com/user-attachments/assets/bf4cfc80-ef5c-4e03-b81d-01c0e9effda9">
<img width="325" alt="image" src="https://github.com/user-attachments/assets/20af3922-1d81-4137-be60-662aa8ec8862">

**Comment by indratrisnar** [comment]
now you can use d_chart 2.9.1 version on pub.dev to solve this issue
