### ISSUE TITLE
horizontal bar, top value is always missing

### ISSUE THREAD

**Issue by dr0-dev** [indratrisnar/d_chart#4]
![Screenshot 2022-07-27 at 16 15 52](https://user-images.githubusercontent.com/70333416/181270069-19df820b-2b32-4f18-a9f3-4f8c3ecdb84f.png)

The green value on top is always hidden, I tried most of the properties but I can't seem to show it.
Is there any way to show it?

**Comment by indratrisnar** [comment]
have you try LabelPosition.outside ?

Pada tanggal Rab, 27 Jul 2022 pukul 21.16 dro-dev ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
sorry, i mean have you try LabelPositio.auto
so it can be outside or inside automatically. when space available to show
label

Pada tanggal Kam, 28 Jul 2022 pukul 08.30 Indra Trisna <
***@***.***> menulis:
