### ISSUE TITLE
use datetime values for x-axis in line-chart

### ISSUE THREAD

**Issue by eggzotic** [indratrisnar/d_chart#6]
Hi, loving this package for graphs in flutter!

Just 1 thing though: if my x-axis values ('domain') are date-stamps I get an error that they must be type num. Could it be possible to use DateTime values there instead?

**Comment by eggzotic** [comment]
Yeah, we can replace the time-data with something like seconds-since-epoch - so it's now a numeric value and the graph works - but this makes the labels on the x-axis kinda meaningless (who knows how to translate that long number into the original datestamp that was in the data?). If the original data has timestamps which are meaningful and readable. I had a look at the source-code and can see where you've used num. It just means that line-charts are really not useful for time-based data, I guess. Thx anyway.

**Comment by indratrisnar** [comment]
Yes,  for datetime value you must use base package,  charts_flutter.
You can see the example from Google Chart Gallery which this package is
discontinued

Pada tanggal Sel, 1 Nov 2022 02.59, Richard Shepherd <
***@***.***> menulis:

**Comment by indratrisnar** [comment]
updated on d_chart: 2.6.2

you can use DChart Time with code T. like DChartLineT, DChartBarT, DChartComboT, DChartScatterT
