### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. 

### ISSUE THREAD

**Issue by antonio-pedro99** [indratrisnar/d_chart#7]
This warning is being caused in ChartContainer.

Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. ../…/src/chart_container.dart:205 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/scheduler/binding.dart'). package:flutter/…/scheduler/binding.dart:1     if (!SchedulerBinding.instance!.hasScheduledFrame ..

**Comment by danielbotn** [comment]
d_chart uses charts_flutter as a dependency. That package is now obsolete and is no longer maintained.

One workaround that d_chart could do is not remove charts_flutter and replace it with https://pub.dev/packages/community_charts_flutter which is a clone of charts_flutter but with fixed issues, also the issue that @antonio-pedro99 mentions above.

**Comment by indratrisnar** [comment]
Thanks for your information,  d_chart will be updated asap

Pada tanggal Rab, 30 Nov 2022 16.27, Daniel Freyr Sigurdsson <
***@***.***> menulis:

**Comment by antonio-pedro99** [comment]
@indratrisnar thanks for your answer. The issue has been fixed.
